### PR TITLE
StreamAuth.c: drop empty non-void function STREAMAuthValueFile return…

### PR DESCRIPTION
**Pull request by andreasstieger**
…ing nothing

drop empty function, triggering warning/errors on non-void return

### CODE REVIEW

**Comment by ColumPaget** [comment]
Ah, this is a placeholder function, one day it will become something.

Clearly I need to start using the compile flags that you're using though! My compiler isn't telling me about any of this stuff.

**Comment by andreasstieger** [comment]
Some of this is distribution specific, but you will see the hardening items below.

````
[   10s] + CFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g'
[   10s] + export CFLAGS
[   10s] + CXXFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g'
[   10s] + export CXXFLAGS
[   10s] + FFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g '
[   10s] + export FFLAGS
[   10s] + FCFLAGS='-O2 -Wall -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=3 -fstack-protector-strong -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -Werror=return-type -flto=auto -g '
[   10s] + export FCFLAGS
[   10s] + LDFLAGS=-flto=auto
[   10s] + export LDFLAGS
[   10s] + ./configure --host=x86_64-suse-linux-gnu --build=x86_64-suse-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info
````

**Comment by ColumPaget** [comment]
Hmm, it might be worth building hardening as an option in libUseful's autoconf setup. I've been fighting with autoconf a lot recently, so I'm a bit more familiar with it now.

**Comment by ColumPaget** [comment]
Function now returns a value (and will contain code in the future, promise!).

Also added autoconf options to turn on -Wall, -Werror -D_FORTIFY_SOURCE and -fstack-protector-strong. Haven't been through and dealt with all the complaints of -Wall yet though.

**Comment by ColumPaget** [comment]
Hi Andreas, I'm thinking of moving libUseful to LGPL (lesser GPL) so people can use it even with private/closed code. I have to get permission from contributors though that they're okay with their contributesion being moved to LGPL. Are you okay with this?

**Comment by andreasstieger** [comment]
The PR proposed to delete a function, and was not even merged. None of my code is in the library, so a re-licensing is not blocked on this. But if it were I would be okay with LGPL too.

**Comment by ColumPaget** [comment]
Oh, you've got code int he library, "Remove spurious executable permissions" for instance. Okay, maybe that's not exactly code, but you show up as a contributor, and I think I "merged" some suggestions of yours "by hand" if you know what I mean (soname for instance).

Anyways, thanks for the quick reply, I'll be moving to LGPL on the next release.

**Pull request closed without merging**
